#!/usr/bin/env node
/* VI One / Rigid Point Advisory — static multilingual site builder.
 *
 *   node _i18n/build.mjs            # writes every locale page + sitemap.xml
 *   node _i18n/build.mjs --check    # builds into memory and reports diffs only
 *
 * Adding a language:
 *   1. copy _i18n/content/en.json to _i18n/content/<code>.json and translate it
 *   2. add one row to _i18n/locales.json
 *   3. run this script
 * hreflang, the sitemap, the language picker and the locale routing are all
 * generated from locales.json, so there is nothing else to keep in sync.
 *
 * The Korean page is hand-written (it is the company page, not the product
 * page). This script only rewrites the marked blocks inside it:
 *   <!--i18n:head--> … <!--/i18n:head-->
 *   <!--i18n:switcher--> … <!--/i18n:switcher-->
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const CHECK = process.argv.includes('--check');

const cfg = JSON.parse(readFileSync(join(HERE, 'locales.json'), 'utf8'));
const LOCALES = cfg.locales;
const byCode = Object.fromEntries(LOCALES.map(l => [l.code, l]));
const FALLBACK = LOCALES.find(l => l.isDefaultForRest) || byCode[cfg.defaultLocale];

const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
/* content may carry <em>, <b> and <br> on purpose; everything else is escaped */
const rich = s => esc(s).replace(/&lt;(\/?)(em|b|br|strong)( ?\/)?&gt;/g, '<$1$2$3>');

/* ── shared fragments ───────────────────────────────────────────────── */

const APPLE_SVG = (w, h, fill) =>
  `<svg width="${w}" height="${h}" viewBox="0 0 24 28" fill="${fill}" aria-hidden="true"><path d="M17.6 14.8c0-3 2.4-4.4 2.5-4.5-1.4-2-3.5-2.3-4.3-2.3-1.8-.2-3.5 1.1-4.4 1.1-.9 0-2.3-1.1-3.8-1-2 .03-3.8 1.1-4.8 2.9-2 3.5-.5 8.8 1.5 11.7 1 1.4 2.1 3 3.6 2.9 1.4-.06 2-.9 3.7-.9s2.2.9 3.8.9c1.6 0 2.5-1.4 3.5-2.8 1.1-1.6 1.5-3.2 1.6-3.3-.03-.02-3-1.2-3-4.7zM14.9 5.6c.8-1 1.3-2.3 1.2-3.6-1.1.04-2.5.8-3.3 1.7-.7.8-1.4 2.2-1.2 3.4 1.2.1 2.5-.6 3.3-1.5z"/></svg>`;

function hreflangBlock(self) {
  const lines = [`<link rel="canonical" href="${cfg.site}${self.path}">`];
  for (const l of LOCALES) lines.push(`<link rel="alternate" hreflang="${l.htmlLang}" href="${cfg.site}${l.path}">`);
  lines.push(`<link rel="alternate" hreflang="x-default" href="${cfg.site}${byCode[cfg.defaultLocale].path}">`);
  return lines.join('\n');
}

/* Language routing. The apex (default locale) reads the visitor's browser
   languages and forwards them once; every other locale is an explicit URL and
   never bounces a visitor off it. A choice made in the picker always wins and
   is remembered. Set AUTO to false on the apex to switch detection off. */
function routingScript(self) {
  const table = LOCALES.map(l => `{c:'${l.code}',p:'${l.path}',m:${JSON.stringify(l.match)}}`).join(',');
  const auto = self.code === cfg.defaultLocale;
  return `<script>
/* Language routing — generated by _i18n/build.mjs, do not edit by hand.
   AUTO=true only on the apex page: it forwards a first-time visitor to the
   page matching their browser language. Set it to false to turn detection off;
   the language picker and hreflang keep working either way. */
(function(){
  var AUTO = ${auto};
  var HERE = '${self.code}';
  var L = [${table}];
  var FALLBACK = '${FALLBACK.code}';
  var KEY = 'rpaLang', ONCE = 'rpaAuto';
  function pathOf(c){ for(var i=0;i<L.length;i++) if(L[i].c===c) return L[i].p; return null; }
  function known(c){ return !!pathOf(c); }
  try{
    var store=null; try{ store=window.localStorage; store.getItem(KEY); }catch(e){ store=null; }
    var forced=(location.search.match(/[?&]lang=([a-z]{2})\\b/)||[])[1]||null;
    var want=null;
    if(forced && known(forced)){
      want=forced;
      if(store){ store.setItem(KEY,want); store.setItem(ONCE,'1'); }
      if(history.replaceState) history.replaceState(null,'',location.pathname+location.hash);
    } else {
      var saved=store&&store.getItem(KEY);
      if(saved && known(saved)){ want=saved; }
      else if(AUTO && !(store&&store.getItem(ONCE))){
        var langs=navigator.languages&&navigator.languages.length?navigator.languages:[navigator.language||''];
        outer: for(var i=0;i<langs.length;i++){
          var tag=(langs[i]||'').toLowerCase();
          for(var j=0;j<L.length;j++) for(var k=0;k<L[j].m.length;k++){
            var m=L[j].m[k];
            if(tag===m||tag.indexOf(m+'-')===0){ want=L[j].c; break outer; }
          }
        }
        if(!want) want=FALLBACK;
        if(store) store.setItem(ONCE,'1');
      }
    }
    if(AUTO && want && want!==HERE) location.replace(pathOf(want));
  }catch(e){}
})();
</script>`;
}

function switcher(self) {
  const opts = LOCALES.map(l =>
    `<option value="${l.path}?lang=${l.code}"${l.code === self.code ? ' selected' : ''} lang="${l.htmlLang}">${esc(l.native)}</option>`
  ).join('');
  return `<span class="lang"><span class="globe" aria-hidden="true">🌐</span><select id="langPick" aria-label="Language">${opts}</select></span>`;
}
const SWITCHER_JS = `<script>(function(){var s=document.getElementById('langPick');if(s)s.onchange=function(){location.href=s.value;};})();</script>`;

/* the picker's own styling, injected into the hand-written page so it does not
   have to carry a copy of these rules (generated pages get them from page.css) */
const SWITCHER_CSS = `<style>
.lang{display:inline-flex;align-items:center;gap:5px;border:1.6px solid var(--line);border-radius:10px;padding:0 9px 0 10px;height:36px}
.lang:focus-within{border-color:var(--navy)}
.lang .globe{font-size:13px;line-height:1;opacity:.75}
.lang select{border:0;background:transparent;font:700 13.5px/1 inherit;color:var(--ink);padding:6px 2px;cursor:pointer;
  -webkit-appearance:none;appearance:none;max-width:104px;text-overflow:ellipsis}
.lang select:focus{outline:none}
footer .ko .dot{margin:0 9px;color:var(--line)}
/* 선택기가 들어오면서 좁은 화면에서 nav 링크가 두 줄로 밀리는 것을 막는다 */
nav a.l{white-space:nowrap}
@media(max-width:640px){.lang{padding:0 6px 0 8px}.lang select{max-width:82px;font-size:13px}}
@media(max-width:400px){nav{gap:5px}.lang{padding:0 4px 0 5px;height:34px}.lang .globe{display:none}.lang select{max-width:62px;font-size:12.5px}nav .cta{padding:8px 10px;font-size:13px}nav .dl{padding:8px 9px}nav a.l{font-size:13.5px}.logo{font-size:18px;gap:7px}.logo img{width:26px;height:26px}.logo img + span{display:none}}
/* 320px 급 구형 단말: 마지막 여유분까지 줄인다 */
@media(max-width:345px){nav{gap:4px}.lang{padding:0 3px}.lang select{max-width:54px;font-size:12px}nav .cta{padding:8px 9px;font-size:12.5px}nav a.l{font-size:12.5px}}
@media(max-width:325px){nav{gap:3px}.logo img{width:20px;height:20px}.lang{padding:0 2px}.lang select{max-width:44px}nav .cta{padding:7px 8px;font-size:12px}nav a.l{font-size:12px}}
</style>`;

function footerLangs(self) {
  return `<div class="ko">` + LOCALES.filter(l => l.code !== self.code)
    .map(l => `<a href="${l.path}?lang=${l.code}" hreflang="${l.htmlLang}" lang="${l.htmlLang}">${esc(l.native)}</a>`)
    .join('<span class="dot">\u00b7</span>') + `</div>`;
}

/* ── page CSS (shared by every generated locale) ─────────────────────── */
const CSS = readFileSync(join(HERE, 'page.css'), 'utf8');

/* ── page assembly ──────────────────────────────────────────────────── */
function buildPage(loc, c) {
  const S = cfg.site, APP = cfg.appStore;
  const card = x => `    <div class="card"><div class="ic">${x.icon}</div><h3>${rich(x.h3)}</h3>
      <p>${rich(x.p)}</p>${x.note ? `\n      <p class="note">${rich(x.note)}</p>` : ''}</div>`;
  const feat = x => `        <li><span class="ck">✓</span><span><b>${rich(x.b)}</b> ${rich(x.t)}</span></li>`;
  const pill = x => `<span class="pill">${esc(x)}</span>`;
  const honest = x => `    <li><span class="x">✕</span><span><b>${rich(x.b)}</b> <span class="t">${rich(x.t)}</span></span></li>`;
  const li = x => `        <li>${rich(x)}</li>`;

  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'Organization', '@id': S + '/#org', name: 'Rigid Point Advisory', alternateName: 'RPA',
        url: S + '/', email: cfg.email, logo: S + '/assets/img/app-icon.svg', description: c.schema.org,
        founder: { '@type': 'Person', name: 'Sangwoo Park', alternateName: '박상우', jobTitle: c.who.role },
        address: { '@type': 'PostalAddress', addressLocality: 'Seoul', addressCountry: 'KR' } },
      { '@type': 'WebPage', '@id': `${S}${loc.path}#page`, url: S + loc.path, name: c.meta.title,
        inLanguage: loc.ogLocale.replace('_', '-'), isPartOf: { '@id': S + '/#org' } },
      { '@type': 'SoftwareApplication', '@id': `${S}${loc.path}#vione`, name: c.schema.appName,
        applicationCategory: 'BusinessApplication', operatingSystem: 'iOS',
        inLanguage: loc.ogLocale.replace('_', '-'), author: { '@id': S + '/#org' },
        installUrl: APP, sameAs: [APP], description: c.schema.appDesc,
        featureList: c.what.cards.map(x => x.h3),
        offers: { '@type': 'Offer', name: c.pricing.starter.name, price: '0', priceCurrency: 'USD',
                  description: c.pricing.starter.fine } }
    ]
  };

  return `<!doctype html>
<html lang="${loc.htmlLang}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(c.meta.title)}</title>
<meta name="description" content="${esc(c.meta.description)}">
${hreflangBlock(loc)}
${routingScript(loc)}
<meta property="og:type" content="website"><meta property="og:site_name" content="Rigid Point Advisory">
<meta property="og:locale" content="${loc.ogLocale}">${LOCALES.filter(l => l.code !== loc.code).map(l => `<meta property="og:locale:alternate" content="${l.ogLocale}">`).join('')}
<meta property="og:title" content="${esc(c.meta.title)}">
<meta property="og:url" content="${S}${loc.path}">
<meta property="og:description" content="${esc(c.meta.ogDescription || c.meta.description)}">
<meta property="og:image" content="${S}/assets/img/og.png"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/assets/img/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/assets/img/apple-touch-icon.png">
<link rel="preconnect" href="https://cdn.jsdelivr.net">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css">
<style>
${CSS}</style>
<script type="application/ld+json">${JSON.stringify(ld)}</script>
</head>
<body>

<header><div class="wrap"><nav>
  <a class="logo" href="${loc.path}"><span>RPA<b>.</b></span></a>
  <span class="sp"></span>
  <a class="l hide" href="#what">${esc(c.nav.what)}</a>
  <a class="l hide" href="#pricing">${esc(c.nav.pricing)}</a>
  <a class="dl" href="${APP}" aria-label="${esc(c.nav.getAppAria)}">${APPLE_SVG(17, 20, 'currentColor')}<span>${esc(c.nav.getApp)}</span></a>
  ${switcher(loc)}
  <a class="cta" href="#contact">${esc(c.nav.contact)}</a>
</nav></div></header>

<div class="hero"><div class="wrap">
  <div class="kick">${esc(c.hero.kick)}</div>
  <h1>${rich(c.hero.h1)}</h1>
  <p>${rich(c.hero.sub)}</p>
  <div class="btns">
    <a class="btn p" href="${APP}">${APPLE_SVG(17, 20, 'currentColor')}${esc(c.hero.btnDownload)}</a>
    <a class="btn g" href="#what">${esc(c.hero.btnSee)}</a>
    <a class="btn g" href="#contact">${esc(c.hero.btnEmail)}</a>
  </div>
</div></div>

<section id="what"><div class="wrap">
  <div class="eyebrow">${esc(c.what.eyebrow)}</div>
  <h2>${rich(c.what.h2)}</h2>
  <p class="lead">${rich(c.what.lead)}</p>
  <div class="grid">
${c.what.cards.map(card).join('\n')}
  </div>
</div></section>

<section id="look" class="soft"><div class="wrap">
  <div class="eyebrow">${esc(c.look.eyebrow)}</div>
  <h2>${rich(c.look.h2)}</h2>
  <div class="prod">
    <div>
      <p class="lead">${rich(c.look.lead)}</p>
      <ul class="feat">
${c.look.feats.map(feat).join('\n')}
      </ul>
      <a class="appbtn" href="${APP}">
        ${APPLE_SVG(24, 28, '#fff')}
        <span><span class="t1">${esc(c.look.appbtnTop)}</span><br><span class="t2">App Store</span></span>
      </a>
    </div>
    <div>
      <div class="shots">
        <img src="/assets/img/en/screen-dash.png" alt="${esc(c.look.alts[0])}" width="590" height="1281" loading="lazy">
        <img src="/assets/img/en/screen-risk.png" alt="${esc(c.look.alts[1])}" width="590" height="1281" loading="lazy">
        <img src="/assets/img/en/screen-client.png" alt="${esc(c.look.alts[2])}" width="590" height="1281" loading="lazy">
      </div>
      <div class="shotcap">${esc(c.look.shotcap)}</div>
    </div>
  </div>
</div></section>

<section id="who-for"><div class="wrap">
  <div class="eyebrow">${esc(c.whoFor.eyebrow)}</div>
  <h2>${rich(c.whoFor.h2)}</h2>
  <p class="lead">${rich(c.whoFor.lead)}</p>
  <div class="pills">${c.whoFor.pills.map(pill).join('')}</div>
</div></section>

<section class="soft"><div class="wrap">
  <div class="eyebrow">${esc(c.honest.eyebrow)}</div>
  <h2>${rich(c.honest.h2)}</h2>
  <p class="lead">${rich(c.honest.lead)}</p>
  <ul class="honest">
${c.honest.items.map(honest).join('\n')}
  </ul>
</div></section>

<section id="pricing"><div class="wrap">
  <div class="eyebrow">${esc(c.pricing.eyebrow)}</div>
  <h2>${rich(c.pricing.h2)}</h2>
  <p class="lead">${rich(c.pricing.lead)}</p>
  <div class="plans">
    <div class="plan hl">
      <h3>${esc(c.pricing.starter.name)}</h3>
      <div class="amt">${esc(c.pricing.starter.amt)}</div>
      <ul>
${c.pricing.starter.items.map(li).join('\n')}
      </ul>
      <div class="fine">${rich(c.pricing.starter.fine)}</div>
    </div>
    <div class="plan">
      <h3>${esc(c.pricing.pro.name)}</h3>
      <div class="amt">${esc(c.pricing.pro.amt)} <small>${esc(c.pricing.pro.amtSmall)}</small></div>
      <ul>
${c.pricing.pro.items.map(li).join('\n')}
      </ul>
      <div class="fine">${rich(c.pricing.pro.fine)}</div>
    </div>
  </div>
</div></section>

<section class="soft"><div class="wrap">
  <div class="eyebrow">${esc(c.who.eyebrow)}</div>
  <h2>${rich(c.who.h2)}</h2>
  <div class="who">
    <div class="avatar">SP</div>
    <div>
      <h3>${esc(c.who.name)}</h3>
      <div class="role">${esc(c.who.role)} — ${esc(c.who.place)}</div>
      <p>${rich(c.who.p1)}</p>
      <p>${rich(c.who.p2)}</p>
    </div>
  </div>
</div></section>

<section id="contact" class="contact"><div class="wrap">
  <div class="eyebrow" style="color:var(--blue2)">${esc(c.contact.eyebrow)}</div>
  <h2>${rich(c.contact.h2)}</h2>
  <p class="lead">${rich(c.contact.lead)}</p>
  <div class="rows">
    <div>✉️ <a href="mailto:${cfg.email}">${cfg.email}</a></div>
    <div>📱 <a href="${APP}">${esc(c.contact.appLink)}</a></div>
  </div>
</div></section>

<footer><div class="wrap">
  <div><strong>Rigid Point Advisory</strong> — ${esc(c.footer.tagline)}</div>
  <div class="biz">
    <span>${esc(c.footer.founder)}</span>
    <span>${esc(c.footer.bizLabel)} ${cfg.bizNo}</span>
    <span>${esc(c.footer.place)}</span>
    <span>${cfg.email}</span>
  </div>
  ${footerLangs(loc)}
  <div style="margin-top:18px">© <span id="y">2026</span> Rigid Point Advisory</div>
</div></footer>
<script>document.getElementById('y').textContent=new Date().getFullYear()</script>
${SWITCHER_JS}
</body></html>
`;
}

/* ── the hand-written Korean page: only the marked blocks are rewritten ── */
function patchHandwritten(loc) {
  const p = join(ROOT, loc.file);
  let s = readFileSync(p, 'utf8');
  const blocks = {
    head: hreflangBlock(loc) + '\n' + SWITCHER_CSS + '\n' + routingScript(loc),
    switcher: switcher(loc) + SWITCHER_JS,
    footerlangs: footerLangs(loc)
  };
  for (const [name, body] of Object.entries(blocks)) {
    const re = new RegExp(`(<!--i18n:${name}-->)[\\s\\S]*?(<!--/i18n:${name}-->)`);
    if (!re.test(s)) throw new Error(`${loc.file}: missing <!--i18n:${name}--> … <!--/i18n:${name}--> markers`);
    s = s.replace(re, `$1\n${body}\n$2`);
  }
  return { path: p, out: s };
}

/* lastmod only moves for a page whose HTML actually changed in this build —
   otherwise the previous value is carried over, so re-running the build on a
   later day is a no-op rather than a diff. */
function previousLastmods() {
  const out = {};
  try {
    const xml = readFileSync(join(ROOT, 'sitemap.xml'), 'utf8');
    for (const m of xml.matchAll(/<loc>([^<]+)<\/loc>[\s\S]*?<lastmod>([\d-]+)<\/lastmod>/g)) {
      const path = m[1].replace(cfg.site, '');
      const loc = LOCALES.find(l => l.path === path);
      if (loc) out[loc.code] = m[2];
    }
  } catch { /* no sitemap yet */ }
  return out;
}

function sitemap(lastmods) {
  const alt = LOCALES.map(l => `    <xhtml:link rel="alternate" hreflang="${l.htmlLang}" href="${cfg.site}${l.path}"/>`).join('\n')
    + `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${cfg.site}${byCode[cfg.defaultLocale].path}"/>`;
  const today = new Date().toISOString().slice(0, 10);
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${LOCALES.map((l, i) => `  <url><loc>${cfg.site}${l.path}</loc>
${alt}
    <lastmod>${lastmods[l.code] || today}</lastmod><changefreq>monthly</changefreq><priority>${i === 0 ? '1.0' : '0.9'}</priority></url>`).join('\n')}
</urlset>
`;
}

/* ── run ────────────────────────────────────────────────────────────── */
const writes = [];
for (const loc of LOCALES) {
  if (loc.source === 'handwritten') { writes.push(patchHandwritten(loc)); continue; }
  const cPath = join(HERE, 'content', `${loc.code}.json`);
  if (!existsSync(cPath)) { console.error(`  skip ${loc.code}: no content/${loc.code}.json`); continue; }
  writes.push({ path: join(ROOT, loc.file), out: buildPage(loc, JSON.parse(readFileSync(cPath, 'utf8'))) });
}
/* decide each page's lastmod before the sitemap is built */
const prev = previousLastmods();
const today = new Date().toISOString().slice(0, 10);
const lastmods = {};
for (const loc of LOCALES) {
  const w = writes.find(x => x.path === join(ROOT, loc.file));
  const before = w && existsSync(w.path) ? readFileSync(w.path, 'utf8') : null;
  lastmods[loc.code] = (w && before === w.out && prev[loc.code]) ? prev[loc.code] : today;
}
writes.push({ path: join(ROOT, 'sitemap.xml'), out: sitemap(lastmods) });

let changed = 0;
for (const w of writes) {
  const before = existsSync(w.path) ? readFileSync(w.path, 'utf8') : null;
  const same = before === w.out;
  if (!same) changed++;
  if (!CHECK && !same) { mkdirSync(dirname(w.path), { recursive: true }); writeFileSync(w.path, w.out); }
  console.log(`  ${same ? 'same  ' : CHECK ? 'DIFF  ' : 'write '} ${w.path.replace(ROOT + '/', '')}  (${w.out.length.toLocaleString()} bytes)`);
}
console.log(CHECK ? `\n${changed} file(s) would change.` : `\n${changed} file(s) written, ${writes.length - changed} unchanged.`);
